spring:
  application:
    name: hotel-booking-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}


  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true
    default-encoding: UTF-8

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

app:
  frontend:
    url: ${APP_FRONTEND_URL}
  mail:
    from: ${APP_MAIL_FROM}
  verify-email:
    expiration: ${APP_VERIFY_TOKEN_EXPIRATION}
    prefix: ${APP_VERIFY_TOKEN_PREFIX}
  jwt:
    secret: ${APP_JWT_SECRET}
    access-expiration: ${APP_JWT_ACCESS_EXPIRATION}
  cookie:
    refresh:
      name: ${APP_COOKIE_REFRESH_NAME}
      secure: ${APP_COOKIE_REFRESH_SECURE}
      same-site: ${APP_COOKIE_REFRESH_SAME_SITE}
      path: ${APP_COOKIE_REFRESH_PATH}

server:
  port: 8080
  servlet:
    context-path: "/api"